const express = require("express");
const app = express();
const cors = require("cors");
const PORT = 8000;

app.use(cors());

const whiskies = {
  auchriosk: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 7.45,
  },
  "balmenach 2006": {
    type: "Scotch",
    composition: "Single Malt",
    age: 8,
    vintage: 2006,
    percent: 46,
    origin: "Speyside",
    price: 6.3,
  },
  "balvenie caribbean cask": {
    type: "Scotch",
    composition: "Single Malt",
    age: 14,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 6.7,
  },
  balvenie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 5.75,
  },
  "allt a bhainne": {
    type: "Scotch",
    composition: "Single Malt",
    age: 15,
    vintage: 2006,
    percent: 46,
    origin: "Speyside",
    price: 9.65,
  },
  aultmore: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 46,
    origin: "Speyside",
    price: 6.8,
  },
  cardhu: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 6.5,
  },
  "glenfarclas 10": {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 5.75,
  },
  "glenfarclas 21": {
    type: "Scotch",
    composition: "Single Malt",
    age: 21,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 12.35,
  },
  bennrinnes: {
    type: "Scotch",
    composition: "Single Malt",
    age: 15,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 5.5,
  },
  glenfiddich: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 5.0,
  },
  speyburn: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 5.1,
  },
  "macallan gold": {
    type: "Scotch",
    composition: "Single Malt",
    age: 21,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 6.3,
  },
  "braeval 1995": {
    type: "Scotch",
    composition: "Single Malt",
    age: 8,
    vintage: 1995,
    percent: 46,
    origin: "Speyside",
    price: 9.3,
  },
  glenlivet: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 5.2,
  },
  craigellachie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 13,
    vintage: "n/a",
    percent: 46,
    origin: "Speyside",
    price: 6.9,
  },
  benromach: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 57,
    origin: "Speyside",
    price: 5.6,
  },
  "glen elgin": {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 6.0,
  },
  "glen keith": {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 9.2,
  },
  "glen moray": {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 5.6,
  },
  benriach: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 4.7,
  },
  "glen spey": {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 6.8,
  },
  glenburgie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 7,
    vintage: "n/a",
    percent: 48.4,
    origin: "Speyside",
    price: 5.35,
  },
  glendullan: {
    type: "Scotch",
    composition: "Single Malt",
    age: 17,
    vintage: "n/a",
    percent: 50,
    origin: "Speyside",
    price: 8.7,
  },
  glenlossie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 7.2,
  },
  glentauchers: {
    type: "Scotch",
    composition: "Single Malt",
    age: 18,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 10.8,
  },
  inchgower: {
    type: "Scotch",
    composition: "Single Malt",
    age: 14,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 7.2,
  },
  kininvie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 17,
    vintage: "n/a",
    percent: 42.6,
    origin: "Speyside",
    price: 30.9,
  },
  knockando: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 4.9,
  },
  linkwood: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 7.5,
  },
  "longmorn distiller's choice": {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 2004,
    percent: 40,
    origin: "Speyside",
    price: 6.0,
  },
  longmorn: {
    type: "Scotch",
    composition: "Single Malt",
    age: 18,
    vintage: "n/a",
    percent: 48,
    origin: "Speyside",
    price: 9.4,
  },
  "macduff old particular": {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 48.4,
    origin: "Speyside",
    price: 10.0,
  },
  mannochmore: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 7.2,
  },
  miltonduff: {
    type: "Scotch",
    composition: "Single Malt",
    age: 17,
    vintage: "n/a",
    percent: 54.8,
    origin: "Speyside",
    price: 8.3,
  },
  "mortlach rare old": {
    type: "Scotch",
    composition: "Single Malt",
    age: "n/a",
    vintage: "n/a",
    percent: 43.4,
    origin: "Speyside",
    price: 8.0,
  },
  singleton: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 6.0,
  },
  strathisila: {
    type: "Scotch",
    composition: "Single Malt",
    age: 15,
    vintage: "n/a",
    percent: 56.4,
    origin: "Speyside",
    price: 15.2,
  },
  tamdhu: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 43,
    origin: "Speyside",
    price: 4.9,
  },
  "tamnavulin double cask": {
    type: "Scotch",
    composition: "Single Malt",
    age: "n/a",
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 11.55,
  },
  tomintoul: {
    type: "Scotch",
    composition: "Single Malt",
    age: 16,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 6.4,
  },
  tormore: {
    type: "Scotch",
    composition: "Single Malt",
    age: 14,
    vintage: "n/a",
    percent: 40,
    origin: "Speyside",
    price: 8.15,
  },
  "auchentoshan 3 wood": {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 43,
    origin: "Lowlands",
    price: 8.0,
  },
  "auchentoshan american oak": {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Lowlands",
    price: 4.8,
  },
  "ailsa bay sweet smoke": {
    type: "Scotch",
    composition: "Single Malt",
    age: "n/a",
    vintage: "n/a",
    percent: 40,
    origin: "Lowlands",
    price: 8.0,
  },
  bladnoch: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: "n/a",
    percent: 40,
    origin: "Lowlands",
    price: 13.7,
  },
  glenkinchie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Lowlands",
    price: 5.4,
  },
  arberlour: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Highlands",
    price: 4.5,
  },
  ancnoc: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Highlands",
    price: 5.3,
  },
  aberfeldy: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: "n/a",
    percent: 40,
    origin: "Highlands",
    price: 5.6,
  },
  "ardmore legacy": {
    type: "Scotch",
    composition: "Single Malt",
    age: "n/a",,
    vintage: "n/a",
    percent: 40,
    origin: "Highlands",
    price: 5.30,
  },
  "balblair 2003": {
    type: "Scotch",
    composition: "Single Malt",
    age: 11,
    vintage: 2003,
    percent: 46,
    origin: "Highlands",
    price: 6.50,
  },
  'dalwhinnie 15': {
    type: "Scotch",
    composition: "Single Malt",
    age: 15,
    vintage: "n/a",
    percent: 43,
    origin: "Highlands",
    price: 6.0,
  },
  'glenglassaugh torfa': {
    type: "Scotch",
    composition: "Single Malt",
    age: "n/a",
    vintage: 2014,
    percent: 46,
    origin: "Highlands",
    price: 6.0,
  },
  'glen garioch': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 48,
    origin: "Highlands",
    price: 6.60,
  },
  'blair atholl': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 7.4,
  },
  'ben nevis': {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: 'n/a',
    percent: 46,
    origin: "Highlands",
    price: 6.0,
  },
  clynelish: {
    type: "Scotch",
    composition: "Single Malt",
    age: 14,
    vintage: 'n/a',
    percent: 46,
    origin: "Highlands",
    price: 6.70,
  },
  'dalmore 12': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 7.0,
  },
  'dalmore 15': {
    type: "Scotch",
    composition: "Single Malt",
    age: 15,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 8.65,
  },
  'glen ord': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 11.3,
  },
  deanston: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 46.3,
    origin: "Highlands",
    price: 6.2,
  },
  edradour: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 6.2,
  },
  glenmorangie: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 5.6,
  },
  'fettercairn 1997': {
    type: "Scotch",
    composition: "Single Malt",
    age: 20,
    vintage: 1997,
    percent: 46,
    origin: "Highlands",
    price: 8.65,
  },
  glencadam: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: 'n/a',
    percent: 46,
    origin: "Highlands",
    price: 4.8,
  },
  glendronach: {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 6.7,
  },
  'glengoyne 10': {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 5.15,
  },
  'glengoyne 18': {
    type: "Scotch",
    composition: "Single Malt",
    age: 18,
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 11.9,
  },
  'glengoyne 21': {
    type: "Scotch",
    composition: "Single Malt",
    age: 21,
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 16.95,
  },
  'loch lomond': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 46,
    origin: "Highlands",
    price: 4.6,
  },
  'old pulteney': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 4.60,
  },
  'royal brackla': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 5.75,
  },
  'royal lochnagar': {
    type: "Scotch",
    composition: "Single Malt",
    age: 12,
    vintage: 'n/a',
    percent: 40,
    origin: "Highlands",
    price: 8.10,
  },
  teannich: {
    type: "Scotch",
    composition: "Single Malt",
    age: 10,
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 5.40,
  },
  'tomatin tawny port finish': {
    type: "Scotch",
    composition: "Single Malt",
    age: 14,
    vintage: 'n/a',
    percent: 46,
    origin: "Highlands",
    price: 6.90,
  },
  'tullibardine sovereign': {
    type: "Scotch",
    composition: "Single Malt",
    age: 'n/a',
    vintage: 'n/a',
    percent: 43,
    origin: "Highlands",
    price: 5.60,
  },
  'wolfburn aurora': {
    type: "Scotch",
    composition: "Single Malt",
    age: 'n/a',
    vintage: 'n/a',
    percent: 46,
    origin: "Highlands",
    price: 6.80,
  },
  "buffalo trace": {
    type: "Bourbon",
    composition: "Single Malt",
    age: "6-8",
    percent: 40,
    origin: "Kentucky, USA",
  },
  redbreast: {
    type: "Irish Whiskey",
    composition: "Single Pot Still",
    age: "12",
    percent: 40,
    origin: "Ireland",
  },
  "Dry County": {
    type: "Superdry",
    composition: "n/a",
    age: "0",
    vintage: "n/a",
    percent: 0,
    origin: "Knowhere",
  },
};

app.get("/", (req, res) => {
  res.sendFile(__dirname + "/index.html");
});

app.listen(process.env.PORT || PORT, () => {
  console.log(`The server is running on port ${PORT}!`);
});

app.get("/api", (req, res) => {
  res.json(whiskies);
});

app.get("/api/:name", (req, res) => {
  const whiskeyName = req.params.name.toLowerCase();
  if (whiskies[whiskeyName]) {
    res.json(whiskies[whiskeyName]);
  } else {
    res.json(whiskies["Dry County"]);
  }
});
